### PR TITLE
[cleanup] pvrmanager.enabled is gone

### PR DESCRIPTION
**Pull request by stefansaraev**
in krypton, pvrmanager.enabled is no more. pvrmanager is automaticaly started if at least one pvr client is configured and enabled. no point hiding it.

### CODE REVIEW

**Comment by gade01** [comment]
You sure about that? Where did you find that info?

I can still disable PVR in the settings and the bool still exists in guisettings.xml

Maybe it's started if one pvr client is installed, but users can still disable it.

**Comment by stefansaraev** [comment]
absolutely.
https://github.com/xbmc/xbmc/pull/9429

**Comment by stefansaraev** [comment]
rebased. I am not good in this skin stuff. this is just what I use. now I see Pvr.HasTVChannels / Pvr.HasRadioChannels conditions are avialable for skins. uhm

**Comment by gade01** [comment]
I see. Thanks a lot for the info.

I'll remove pvrmanager.enabled, but I can't merge this since this will remove all visible conditions for PVR stuff. If people don't use PVR, then they'll still see these categories, controls etc.

But I'll add something else.

Thanks again for helping out :)

**Comment by stefansaraev** [comment]
:)

**Comment by gade01** [comment]
No worries. Thanks for the heads up. Let me know if you have any other requests.

**Comment by stefansaraev** [comment]
some broken fonts (I opened an issue) /me runs

**Comment by gade01** [comment]
Ah, yeah. I'll take a look at it.

Sorry, been busy with other skin related stuff :)

**Pull request closed without merging**
